### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by redha-ax2lan** [afterlogic/aurora-files#12]
Hello !
I have searched and I don't find folder permission system and have all users have access at all folder in corporate.I need to develop this or a similar system exist?
Thanks have a good day !

**Comment by afterlogic-support** [comment]
Aurora platform offers a multi-tenancy feature, you can enable it by setting **EnableMultiTenant** to **true** in `data/settings/config.json` file. Then you can create new tenants and create different users under different tenants - each tenant will have its own Corporate file pool.

**Comment by yaua** [comment]
Dear team.
How to set folder permission corporate only for group view. I created group in team but it can not work.
Please help me. Thank you!

**Comment by afterlogic-support** [comment]
That's not supported, Corporate file pools can only be separated on per-tenant level.
