### ISSUE TITLE
large file synchronisation

### ISSUE THREAD

**Issue by totoetco** [afterlogic/aurora-files#15]
It seems that large files fail to be synchronized. 

In my superadmin settings, file upload limit is not activated, Tenant space limit is set to 0 and user space limit too. 

Synchronizing small files works fine but synchronization fails for a 208 Mb pdf file for my main and only user. 

[Upload error](https://filesender.breniere.eu/f.php?h=14yJFsA7&p=1)

Thanks for you help.

Thomas

**Comment by afterlogic-support** [comment]
Make sure your PHP configuration allows for uploading large file as well:
https://afterlogic.com/docs/aurora-files/troubleshooting/error-while-uploading-to-files-storage

**Comment by totoetco** [comment]
Hello, thanks for your help.
I'm sorry but there is no php.ini file anywhere in my installation folder.
Should it be located in data/files ?

**Comment by afterlogic-support** [comment]
**php.ini** file isn't a part of Aurora Files, it's where your system has PHP configuration settings stored.
You can view current settings, along with the path of the configuration file, by creating a simple PHP script and opening it from the browser:
```php
<?php phpinfo();
```

**Comment by totoetco** [comment]
Thanks ! 
Then this is another problem that doesn't have anything to do with Aurora Files... I do not have access to those settings because I use a shared hosting service. 
Have a nice day
