### ISSUE TITLE
Storage Limitation

### ISSUE THREAD

**Issue by saalem-git** [afterlogic/aurora-files#16]
Hi,

Aurora Files looks great but I wanted to know storage limitation.
Does it depend on computer storage for localhost? for example, the PC has 100GB available and we are able to store 100GB files (img, video, document.....) or phpmyadmin?
There is limitation for phpmyadmin right?

Thank you

**Comment by afterlogic-support** [comment]
The limitations are set in Aurora Files admin interface. You can configure:
* per-user upload limit for a single file;
* total space allocated for all users;
* default quota for a new user created.

![files-limits](https://user-images.githubusercontent.com/16918936/66029429-f0dc1e00-e507-11e9-94cf-6146439c9089.png)

Actual space available, or configuration of other products do not affect Aurora Files.

**Comment by saalem-git** [comment]
Thank you for the reply
What I mean was is, if we do not set limit, there is no limitation of size for the Aurora files right?
For example, user will be able to upload 1million pdf documents if computer has space right?

**Comment by afterlogic-support** [comment]
Setting limit to 0 will result in unlimited storage, yes.

**Comment by saalem-git** [comment]
Awesome 

Thank you
