### ISSUE TITLE
Cannot increase user space limit  for corporate

### ISSUE THREAD

**Issue by saalem-git** [afterlogic/aurora-files#19]
Hi,

I only can increase personnel space limit for users but for corporate user space limit still 100MB.
As you can see in the below attached images, personnel is 488.3 GB but for corporate is still 100MB.

Can you please help to increase the corporate space limit also?

Thank you
![Screenshot 2019-11-25 at 4 50 24 PM](https://user-images.githubusercontent.com/31685814/69525832-e8eaa880-0fa3-11ea-9f3f-fe338b471bba.png)
![Screenshot 2019-11-25 at 4 49 09 PM](https://user-images.githubusercontent.com/31685814/69525835-ea1bd580-0fa3-11ea-994a-c09063816b5e.png)

**Comment by afterlogic-support** [comment]
Try adjusting `SpaceLimitMb` value in `data/settings/modules/CorporateFiles.config.json` file.

Hope it helps.

**Comment by saalem-git** [comment]
Awesome 
Thank you so much

**Comment by saalem-git** [comment]
Hi 
Sorry to disturb you again
I cannot find CorporateFiles.config.json in the folder
in mac, I searched and found it but in windows it is not in the folder (even I ticked hidden files)

**Comment by afterlogic-support** [comment]
Are you speaking of the file structure of your installation of Aurora Files on the server?
Try clicking "Update configuration" button in "Database Settings" screen of admin interface.
The file should be there under `data/settings/modules/` directory.

**Comment by saalem-git** [comment]
I did not "Update Configuration".
After updating, all files are in  data/settings/modules/

Thank you so much
you are the best
