### ISSUE TITLE
empty - PHP Fatal error: Can't use function return value in write context

### ISSUE THREAD

**Issue by afonsoft** [afterlogic/aurora-files#2]
PHP Fatal error: Can't use function return value in write context in E:\Inetpub\vhosts\afonsoft.com.br\webmail.afonsoft.com.br\system\Module\Manager.php on line 90

Note:
Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.

if (!empty(\trim($sTenant))) ---> Not Ok

**Comment by afonsoft** [comment]
phpinfo

https://nuvem32w.hoteldaweb.com.br:8443/smb/web/php-info/id/1805

**Comment by vasil-sokolov** [comment]
Thank you for this bug report. This issue has already fixed. The new version of Aurora Files will be released in a few days.
