### ISSUE TITLE
File size limit for upload

### ISSUE THREAD

**Issue by Jancs-E** [afterlogic/aurora-files#20]
Hi!
I met strange limit for file uploads - if I try to upload anything over 2 MB, I get the error message saying that "The file cannot be uploaded as it's too big.". No problems for download.

Log file does not contain anything of any value:
[19:21:21.83][c0987cb0] ===== API: Files::UploadFile
[19:21:21.86][c0987cb0] ApiException
[19:21:21.86][c0987cb0] @Time: 0.1682
[19:21:21.86][c0987cb0] @TimeApiInit: 0.1391

My php.ini settings:
post_max_size=200M
upload_max_filesize = 100M
max_file_uploads = 50 

Aurora - UploadSizeLimit 5000 MB

More to the issue:
AttachmentSizeLimit is 0 (CoreWebClient/config.json), it does not change anything if it is set to any other value, it seems it is not evaluated at all in the FilesWebclient.app.c869d887a25c1c225a33.js

Somehow it does not get to detailed error message (msg COREWEBCLIENT/ERROR_UPLOAD_SIZE_DETAILED), it stops somewhere before it as value of size limit is not displayed (msg COREWEBCLIENT/ERROR_UPLOAD_SIZE gets in pop-up).

I even tried to block out iSize valuation in FilesWebclient.app.c869d887a25c1c225a33.js, but w/o results. 
I also tried to follow advice found in other threads, but w/o results
(Apache 2.4.39, php 5.6.40/Linux)

**Comment by afterlogic-support** [comment]
To let us help you on this, please open a ticket in [HelpDesk](https://s.afterlogic.com/helpdesk) and provide us with your installation URL and a test account we can reproduce the issue on. Thanks.
