### ISSUE TITLE
User specific space limit does not apply

### ISSUE THREAD

**Issue by MPNull** [afterlogic/aurora-files#21]
The (user specific) space limit does not apply at all. It doesn't matter do I press Update Configuration. User specific space limit is always the same as setting on newly created user space.

**Comment by afterlogic-support** [comment]
Is the issue reproduced with the latest 8.3.15? Thanks.

**Comment by E-Tamminen** [comment]
Yes.

**Comment by MPNull** [comment]
I have the issue with the 8.3.15.

**Comment by afterlogic-support** [comment]
Please make sure you supply user-specific space limit in `data/settings/modules/Files.config.json` configuration file, **UserSpaceLimitMb** setting. I've just tested this with 8.3.15 and I can confirm the setting works as expected, being applied to new users created.

**Comment by MPNull** [comment]
You don't get it. I was speaking about user-specific settings all of the time. Not new users.

1. If you create a new user. He will be assigned x amount of space (pre-defined) in example a 200MB.
2. He will see 200MB on his quota bar and he can upload a maximum of 200MB files.
3. You go to Administrator Panel and you go Users -> Selected User -> Files -> User space limit -> Change that e.g. 1000MB -> Save
4. He will not see 1000MB on his quota. The quota is still 200MB and he cannot still upload files more than 200MB.

**Comment by afterlogic-support** [comment]
Oh, indeed we were talking about two different things. I have reproduced the issue you reported, and have reported it to the developers. Thank you.

**Comment by MPNull** [comment]
Hey, thank you for that. I'll start using Aurora Files regularly after the issue is fixed. Aurora Files is a good cloud system though.

**Comment by afterlogic-support** [comment]
Just wanted to let you know that developers have corrected the issue. The fix will become available in the next product update. Thanks again!

**Comment by MPNull** [comment]
When do we get the update?

**Comment by afterlogic-support** [comment]
We plan to release it later this week, there's still a couple of issues left to resolve before we can roll out the next version.

**Comment by MPNull** [comment]
Alrighty. Thanks.
