### ISSUE TITLE
Question: share button not shown/How to enable share button.

### ISSUE THREAD

**Issue by JoostFaber** [afterlogic/aurora-files#23]
Hi,

In the live demo there is a button shown to share files from your personal or corporate folder. 
I have installed aurora-files from a package and followed each step of the install guide.
afterwards i have added the "afterlogic/aurora-module-shared-files" which only shows the shared folder but not the share button.
I haven't found any page in the documentation how to enable this.

**share button from live demo**
![share_btn-in_live-demo](https://user-images.githubusercontent.com/11028935/85037923-46d01f00-b186-11ea-97e1-505500e6f9b4.png)

**No share button shown**
![no_share_button](https://user-images.githubusercontent.com/11028935/85037782-17b9ad80-b186-11ea-98e0-0066728e13c1.png)

**Comment by afterlogic-support** [comment]
Currently, Live Demo relfects 8.4.0 release candidate we're going to publish soon.
Still, even in 8.3.* you should be able to add file sharing feature - and aside from adding the module itself, you need to build static files [as shown here](https://afterlogic.com/docs/aurora-files/installation/adding-modules). Hope this helps.
