### ISSUE TITLE
Can't create secure link if js files are minimized

### ISSUE THREAD

**Issue by blackpill** [afterlogic/aurora-files#25]
in the file modules/OpenPgpFilesWebclient/js/views/ButtonView.js line 30:
`
let bIsFile = selectedItem().constructor.name === 'CFileModel';
`
Because the constructor name changed to a simple name after js minimization, the line above is incorrect.
I add a "keep_fnames: true" option for terser plugin to let it work.

**Comment by afterlogic-support** [comment]
The developers have confirmed and corrected the issue, the fix will be available in the next release. Thank you.

**Comment by afterlogic-support** [comment]
The thread is closed due to inactivity. Should the issue persist, please feel free to reopen and provide an update. Thank you.
