### ISSUE TITLE
Custom icons/icon picker

### ISSUE THREAD

**Issue by JoostFaber** [afterlogic/aurora-files#27]
Hi Afterlogic,

We would like to have the ability to give folders their own icon (Font Awesome for example). So not the default blue folder.

Since this feature is currently not available, is this considered in upcoming releases?

**Comment by afterlogic-support** [comment]
We don't currently have such a feature planned. If you may be interested in getting it implemented in terms of custom development contract, please contact us [via HelpDesk](https://s.afterlogic.com/helpdesk). Thank you.
