### ISSUE TITLE
Login redirection loop issue

### ISSUE THREAD

**Issue by dcabezas1** [afterlogic/aurora-files#29]
Good afternoon.
We are performing an aurora files installation and we are trying to access our installation with the superadmin login and blank password but it redirects us to the login again.

On the other hand, sometimes a message appears in red at the top indicating that "it is not configured". Could you give us support? Thank you very much.

Here is a video of the sequence: https://im5.ezgif.com/tmp/ezgif-5-b827e61b1ef0.gif

**Comment by afterlogic-support** [comment]
We've responded to this in our HelpDesk. Thanks.
