### ISSUE TITLE
IMAP login support so that users can login to cloud file with their IMAP username and password on same server

### ISSUE THREAD

**Issue by bsbudhwar** [afterlogic/aurora-files#3]
Hi,

Is aurora files support IMAP login module so that users can login with their IMAP username and password for easy access to files.

Is this module available or you guys are still working on it.

And Theme is not mobile friendly its opening desktop view. 

thanks and regards,

Birender

**Comment by vasil-sokolov** [comment]
Hello
Unfortunately, there is no separate module for authentication via IMAP, but such functionality is present in Mail module. You can add this module (also you will need Mail Webclient module) and get ability to login using mail credentials. Instructions how to do this are available here: [https://afterlogic.com/docs/aurora-files/installation/adding-modules](https://afterlogic.com/docs/aurora-files/installation/adding-modules). Full names of mail modules are "aurora-module-mail" and "aurora-module-webclient-mail".

For the second part of you question, yes, Aurora Files has no mobile friendly UI, but there's native app for iOs and Android platforms. You can find more information about them at Aurora Files home page [https://afterlogic.org/aurora-files](https://afterlogic.org/aurora-files).

Mobile layout of a browser version of Aurora is available in WebMail Pro 8 ( product's home page [https://afterlogic.com/webmail-pro-8](https://afterlogic.com/webmail-pro-8) ). It is a product from the same product family, but a little bit more mail-oriented.

I hope this information will be useful for you.

Best regards,
Vasil Sokolov

**Comment by bsbudhwar** [comment]
Hi Thanks for the reply i added both modules but how to get this IMAP login possible with these modules i mean how to activate that...?

I try to login but its giving me error invalid user-name or password.

How i can login to aurora files with mail server accounts with username and password.

regards,

Birender

**Comment by vasil-sokolov** [comment]
hello now you should configure your installation.
Hello,
First of all, enable auto creation of user accounts on login by changing value of **AllowNewUsersRegister** param to **true** in **/data/settings/modules/Mail.config.json file.**
Next go to admin panel and add Mail Server in appropriate tab.
You should fill **Domains** field in server creation form with domain names or specify asterisk for any domain name.

That should do it.

**Comment by bsbudhwar** [comment]
Hi i made changes to Mail.config.json and still now working when i login to admin i can only see these options please see the attachments
![page2](https://user-images.githubusercontent.com/18082766/32096937-90ddf248-bb25-11e7-892c-ccdcce245409.png)
![page1](https://user-images.githubusercontent.com/18082766/32096938-911c10f0-bb25-11e7-93b3-aa1a0d14ae39.png)

.

**Comment by vasil-sokolov** [comment]
What did you specify as a version of mail modules in modules.json?
Also please check the values of **Disable** parameters in config files of Mail modules. The values should be **false**.

**Comment by bsbudhwar** [comment]
all module having version as 0.5.x

so i also defined like that...
"afterlogic/aurora-module-mail": "0.5.x",
"afterlogic/aurora-module-webclient-mail": "0.5.x"

**Comment by vasil-sokolov** [comment]
Are you sure you did all the steps from **Adding modules** instructions?
I've got mail tabs on a fresh installation of Aurora Files with added Mail modules.
I assume you forgot to build static js files. 
Also it's possible that non-minified js files are used on your installation and you just need to build them by calling **gulp js:build**, calling **gulp js:min** is not enough in this case.
