### ISSUE TITLE
Paranoid encryption not decrypting

### ISSUE THREAD

**Issue by prolomb** [afterlogic/aurora-files#30]
Hi
Using paranoid encryption with PGP in browser files are correctly uploaded on server in encrypted form but when downloading the decryption is not performed automatically and files can not be read
Is this somthing expected? 
Thank you for your support

**Comment by afterlogic-support** [comment]
Hello,
I've reproduced the issue and have reported it to the developers.
Most likely, it will be corrected in the next version expected later this month.
Thank you.

**Comment by prolomb** [comment]
Thank you very much for your support!

**Comment by afterlogic-support** [comment]
We believe the issue has been corrected in the latest version, it can no longer be reproduced at Aurora Files [Live Demo](https://aurora-files.afterlogic.com/). Thank you.
