### ISSUE TITLE
CorporateFiles has no access limitation?

### ISSUE THREAD

**Issue by AndyAlvarezDev** [afterlogic/aurora-files#31]
Inside the configuration file CorporateFiles.config.json there is no where to define user groups, I want to classify the display of files only by users of the same domain name. Is there any chance of achieving this goal?

**Comment by afterlogic-support** [comment]
You can try achieving that by enabling multi-tenancy, that's done by setting "EnableMultiTenant" to **true** in `data/settings/config.json` file. After that, you can add and manage tenants in admin interface, and add users to different tenants. Each tenant would have a separate Corporate file pool, then.
