### ISSUE TITLE
Cannot download file from public link in incognito

### ISSUE THREAD

**Issue by extbe** [afterlogic/aurora-files#33]
Hi!

I use the latest setup for Docker from this repository: https://github.com/afterlogic/docker-aurora-files.

When I try to download a file from public link in incognito mode or via postman I get the following error:
```json
{
    "AuthenticatedUserId": 0,
    "@Time": 0.0176,
    "SubscriptionsResult": null,
    "@TimeApiInit": 0.012,
    "@LoggerGuid": "85747279",
    "ErrorCode": 999,
    "Module": ""
}
```

Also there is an error in the logs from adminpanel:
```
[12:30:24.99][70a0969d]  ===== API: LogsViewerWebclient::GetLogFilesData
[12:30:24.99][70a0969d] @Time: 0.0013
[12:30:24.99][70a0969d] @TimeApiInit: 0.0108
[12:30:24.99][70a0969d] INFO[MEMORY]: Memory peak usage: 4MB
[12:30:24.99][70a0969d] INFO[TIME]: Time delta: 1630585824.9993
[12:30:26.50][85747279] @Time: 0.0176
[12:30:26.50][85747279] @TimeApiInit: 0.012
[12:30:26.50][85747279] Exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'GuestPublicId' cannot be null (SQL: insert into `au_core_activity_history` (`UserId`, `ResourceType`, `ResourceId`, `IpAddress`, `Action`, `Timestamp`, `GuestPublicId`, `UpdatedAt`, `CreatedAt`) values (1, file, personal/amf-1.0.0.tgz, 172.17.0.1, download, 1630585826, ?, 2021-09-02 12:30:26, 2021-09-02 12:30:26))
[12:30:26.50][85747279] INFO[MEMORY]: Memory peak usage: 2MB
[12:30:26.50][85747279] INFO[TIME]: Time delta: 1630585826.5041
```

We can se that the `GuestPublicId` column doesn't accept nulls if we describe the `au_core_activity_history` table. Also there is no default value for the column.
```
MariaDB [afterlogic]> describe au_core_activity_history;
+---------------+---------------------+------+-----+---------+----------------+
| Field         | Type                | Null | Key | Default | Extra          |
+---------------+---------------------+------+-----+---------+----------------+
| Id            | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| UserId        | int(11)             | NO   |     | 0       |                |
| ResourceType  | varchar(255)        | NO   |     |         |                |
| ResourceId    | varchar(255)        | NO   |     |         |                |
| IpAddress     | varchar(255)        | NO   |     | 1       |                |
| Action        | varchar(255)        | NO   |     |         |                |
| Timestamp     | int(11)             | NO   |     | 0       |                |
| GuestPublicId | varchar(255)        | NO   |     |         |                |
| CreatedAt     | timestamp           | YES  |     | NULL    |                |
| UpdatedAt     | timestamp           | YES  |     | NULL    |                |
+---------------+---------------------+------+-----+---------+----------------+
```

I can download a file from public link only when I'm logged in. 

Thanks!

**Comment by afterlogic-support** [comment]
Thank you for the report. I was able to reproduce the issue, have forwarded the information to the developers.

**Comment by extbe** [comment]
Any news on the issue? I think this feature is very popular and all of us (users) will be grateful if you can fix the problem soon 😃

**Comment by extbe** [comment]
After some deep dive into sources I've found the root cause.

The `GuestPublicId` property isn't set in the FilesWebClient module ([here](https://github.com/afterlogic/aurora-module-webclient-files/blob/315ed876582bc87c750db413880b25a48d44d356/Module.php#L75)), but it is used in the `ActivityHistory` module ([here](https://github.com/afterlogic/aurora-module-activity-history/blob/43902e91f839f1dd63b5538e5d2952bb8a67b9e9/Module.php#L56)). As we can see, if the property is not defined, then `null` is used as a default value, but the `au_core_activity_history` table doesn't allow nulls in this column.

Hope this will help. I can also offer a couple of solutions and do a PR, if we will agree on which fix is more appropriate for your business logic.

**Comment by afterlogic-support** [comment]
Spoke to the developers, they agree this should be fixed in the nearest release, and will investigate the issue further. Will keep you posted. Thank you!

**Comment by afterlogic-support** [comment]
Just heard from the developers, they have located and corrected the issue, the fix will be included in the next update. To correct the issue on your installation, please modify `modules/ActivityHistory/Module.php` file, locate the following code in `Create()` function:

```php
$oUser = \Aurora\System\Api::getAuthenticatedUser();
if ($oUser)
{
	$GuestPublicId = $oUser->PublicId;
}
```

and add the following right afterwards:

```php
else
{
	$GuestPublicId = '';
}
```

Hope this helps. Have tested this modification on my local installation, seems to do the trick. Thank you.

**Comment by extbe** [comment]
Thanks for the solution! 

Maybe the date of the next update is already known? :)

**Comment by afterlogic-support** [comment]
Not yet, we're still working on correcting a few issues, the best estimate I currently have is next week.

**Comment by afterlogic-support** [comment]
Aurora Files 9.0.1 has just been released. Thank you!
