### ISSUE TITLE
loginDom is not defined.

### ISSUE THREAD

**Issue by mzch** [afterlogic/aurora-files#34]
I turied to update v8 to v9 or install the latest fom this repository, but the same error prevent to access login form.

<img width="1498" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/136363680-b2364388-356c-42b7-a7fb-fb6998ab05b4.png">

Could you tell me to fix this issue?

- Server
OS: `Debian 11.0`
PHP: `7.4.21`
Node: `v12.22.6`
Aurora-Files: `9.1.0.rc10-build-o2`

- Client
OS: `macOS 11.6 (Intel)`
Browser: Google Chrome: `94.0.4606.71`

**Comment by afterlogic-support** [comment]
It looks like JavaScript code doesn't match the templates used. In the repository, `loginDom` variable is there in both JavaScript and HTML. Make sure you have rebuilt JavaScript static files, see step 5 [here](https://github.com/afterlogic/aurora-files#readme).

**Comment by afterlogic-support** [comment]
Can you confirm what's in the `VERSION` file?
