### ISSUE TITLE
Control over the Cache-Control header

### ISSUE THREAD

**Issue by extbe** [afterlogic/aurora-files#39]
Hi!

Is there an ability to control the `Cache-Control` header value returned from the `{{appUrl}}/?/files-pub/{{hash}}/view` endpoint?
The value is always `no-cache`. Is it possible to mark the response as cacheable usning `public` and `max-age` directives?

Thanks!

**Comment by afterlogic-support** [comment]
According to the developers, that's not configurable, the code is found in `modules/FilesWebclient/Module.php` file, **EntryPub** function.
