### ISSUE TITLE
public link not removed

### ISSUE THREAD

**Issue by rmihaig** [afterlogic/aurora-files#4]
Hello,
i created a folder, set public link, rename folder, remove public link but on refresh the link is still there on the folder.
i tested also regular create folder, create public link, remove link, and on refresh the link is still there.

**Comment by afterlogic-support** [comment]
I have reproduced the issue, developers will take a look. Thanks.

**Comment by afterlogic-support** [comment]
We believe this issue is no longer there in current version of the product. Thanks.
