### ISSUE TITLE
Issue while Composer.phar 

### ISSUE THREAD

**Issue by jayQgroup** [afterlogic/aurora-files#41]
Hello there i am getting issue while installing from git composer
 Problem 1
    - intervention/image is locked to version 2.7.0 and an update of this package was not requested.
    - intervention/image 2.7.0 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
  Problem 2
    - intervention/image 2.7.0 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
    - afterlogic/aurora-framework 0.10.46 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.7.0].
    - afterlogic/aurora-framework is locked to version 0.10.46 and an update of this package was not requested.

i have done all the settings for 
extension=php_fileinfo.dll
and also restarted my apache server

but getting same errors

**Comment by afterlogic-support** [comment]
The ticket is closed due to inactivity. If you believe the issue still exists upon following our suggestions, please post back here. Thanks.
