### ISSUE TITLE
DAV login on MacOS Monterey

### ISSUE THREAD

**Issue by rainingmirrors** [afterlogic/aurora-files#42]
I recently installed Aurora Files on my Web Server. Installation went without any error messages, I can log in on the browser or using the iPad App without a hitch, I can upload and download files via web app perfectly. But trying to access via DAV runs into serious problems, I cannot get a grip on. It doesn't matter, if I try standard WebDAV, CalDAV or CardDAV, I cannot establish a connection to the server via these protocols. Is there anything, I have missed?

Trying to connect via Handshake app on Mac retrieves the error "SSL handshake failed: SSL error: tlsv1 alert protocol version"

**Comment by rainingmirrors** [comment]
Thanks for the fast reply!

I am using a dedicated subdomain, which is https://dav.skopal.cc/ Login should be possible via https://dav.skopal.cc/dav.php/ but it always runs nowhere.

Currently, I have the standard .htaccess file running, which is functioning, changing that to the virtual host configuration breaks the server.

RewriteEngine on
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

<Files *config.json*>
	order allow,deny
	deny from all
</Files>

I’ll check the .well-known access, since this is new to me, I have to read up on that. I’m in contact with my web hosting company as well, to see if there is any issue.

Best regards,
Martin

**Comment by afterlogic-support** [comment]
> I am using a dedicated subdomain, which is https://dav.skopal.cc/ Login should be possible via https://dav.skopal.cc/dav.php/ but it always runs nowhere.

The question is, what domain is Aurora Files itself accessible from? My guess would be https://skopal.cc/ but something else is located there. 

> Currently, I have the standard .htaccess file running, which is functioning, changing that to the virtual host configuration breaks the server.

Virtual host configuration isn't done via .htaccess, you'd need to adjust actual webserver configuration file. As for .well-known access, that one indeed can be setup via .htaccess.

**Comment by afterlogic-support** [comment]
The thread is closed due to inactivity. Should the issue persist, please feel free to reopen and provide an update. Thank you.
