### ISSUE TITLE
Error executing CopyObject  and NoSuchBucket

### ISSUE THREAD

**Issue by zlp886** [afterlogic/aurora-files#44]
Hi there

I am using Aurora-Files using K8S php7.4 and AWS S3 strorage

When i MOVE file to folder
I get this error

Error Message

↓

File moving has failed. (Error executing "CopyObject" on "https://test-default.s3.ap-northeast-1.amazonaws.com/testuser/test/1.jpg"; AWS HTTP error: Client error: `PUT https://test-default.s3.ap-northeast-1.amazonaws.com/testuser/test/1.jpg` resulted in a `404 Not Found` response: <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>toshotest-default.ap-n (truncated...) NoSuchBucket (client): The specified bucket does not exist - <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>test-default.ap-northeast-1</BucketName><RequestId>60QYD4GFXBDY1P</RequestId><HostId>uvZWEFsD04drAavOufaD2IFFmewNGEfhCadlhtyiHd5qoTWn6LpTQ=</HostId></Error>)

BucketName is test-default.
But in error Message , BucketName is test-default.ap-northeast-1

Thank you

**Comment by zlp886** [comment]
public function getCopySource($sKey)
	{
		$sRegion = '';
		if ($this->endsWith($this->client->getEndpoint(), 'amazonaws.com'))
		{
			$sRegion = '.' . $this->client->getRegion();
		}

		return $this->bucket . $sRegion . "/" . \Aws\S3\S3Client::encodeKey($sKey);
	}

if modify
$this->bucket . $sRegion
to
$this->bucket 


MOVE file to folder have no Error

**Comment by afterlogic-support** [comment]
Hello,
Thank you for your feedback, I've asked the developers to take a look.
By the way, can you please confirm your Amazon S3 connection details were specified exactly as described here? 
https://afterlogic.com/docs/aurora-files/configuration/using-amazon-or-digitalocean-s3-instead-of-local-file-storage
Thanks.

**Comment by zlp886** [comment]
Hi
Thank you 

This is my setting of S3

![image](https://user-images.githubusercontent.com/4176355/172813209-5e2c6ead-fa32-45b5-aa9b-13407e50feb8.png)

**Comment by afterlogic-support** [comment]
Thank you. The developers were unable to reproduce such an issue, though, it worked correctly for them, with and without the suggested patch. If possible, please share the access/secret key so we could investigate this further, you can send data privately [via HelpDesk](https://s.afterlogic.com/helpdesk)

**Comment by zlp886** [comment]
Thank you for your reply
I will do test again

**Comment by afterlogic-support** [comment]
OK thank you. Should the issue persist, please contact us [via HelpDesk](https://s.afterlogic.com/helpdesk) and provide us with a way to reproduce the issue.
