### ISSUE TITLE
reCapcha Problem

### ISSUE THREAD

**Issue by zlp886** [afterlogic/aurora-files#46]
Hi there 

When i sabled reCaptcha Plugin 
and 
register a new user 

get this Error

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4176355/173173617-aa734705-fe69-4635-adea-b9043d1dd9d0.png">

There is no reCaptcha on the web page

Thank you for your GOOD JOB

**Comment by afterlogic-support** [comment]
Thank you for the report, I've reproduced the issue and have reported it to the developers.

**Comment by afterlogic-support** [comment]
I believe the issue has been corrected in version 9.7.0 of the product we have just released. Hope the update helps you. Thanks again!
