### ISSUE TITLE
Video Playback

### ISSUE THREAD

**Issue by drdentz** [afterlogic/aurora-files#48]
Is there any way to integrate an embedded playback for uploaded video files, similar to the integration of external Youtube videos?

**Comment by afterlogic-support** [comment]
That's not currently supported. I believe there's such a [feature request](https://afterlogic.uservoice.com/forums/932341-aurora-files/suggestions/45010015-integrate-a-video-player) already, feel free to upvote it. We use that resource when developing product's roadmap, so if the feature gets a good number of votes, there's a better chance of it getting implemented.

Aurora Files is an open-source product, so you can modify it and implement any features you require - or you can [request custom development](https://s.afterlogic.com/) from us.
