### ISSUE TITLE
mobile responsive issues

### ISSUE THREAD

**Issue by rmihaig** [afterlogic/aurora-files#5]
Hello,
if you view images or video, the images are very small and the title is truncated...
video gets out of the screen
tested on galaxy note4

**Comment by afterlogic-support** [comment]
Confirmed. And while Aurora Files doesn't currently offer mobile responsive design, viewing media files should work. We'll see what we can do.

**Comment by rmihaig** [comment]
ok, but in the newsletter it was written "Responsive web interface, available in a number of languages." :)

**Comment by afterlogic-support** [comment]
Oh, you're right, I was thinking about WebMail Lite here. As for viewing files, that looks like a bug and we'll have it fixed soon.

**Comment by afterlogic-support** [comment]
The thread is closed due to inactivity. Should the issue persist, please feel free to reopen and provide an update. Thank you.
