### ISSUE TITLE
Installation requirements

### ISSUE THREAD

**Issue by adiif1** [afterlogic/aurora-files#50]
Hello, can you ask for the best installation requirements? what version of php will be the best ??

under my phpinfo();

`

Version | 7.4.30 | Install Path | /www/server/php/
php.ini | /www/server/php/74/etc/php.ini
Loaded | Core date libxml openssl pcre sqlite3 zlib bcmath ctype curl dom filter ftp gd gettext hash iconv intl json mbstring SPL session pcntl standard PDO mysqlnd pdo_sqlite Phar posix Reflection pdo_mysql shmop SimpleXML soap sockets sodium mysqli sysvsem tokenizer xml xmlreader xmlrpc xmlwriter zip
`

I need memcache?/memcached? Lib FileInfo? or other?

Thanx!

**Comment by afterlogic-support** [comment]
Hello,
[You can find the system requirements at:](https://afterlogic.com/docs/aurora-files/system-requirements)
https://afterlogic.com/docs/aurora-files
You should run Compatibility Test to ensure the installation location meets the requirements:
https://afterlogic.com/docs/aurora-files/installation/compatibility-test
As for PHP version, 7.4 is still supported just fine - use either that or 8.1.
Hope this helps.
