### ISSUE TITLE
Upload file using terminal

### ISSUE THREAD

**Issue by sicenul** [afterlogic/aurora-files#52]
Is it possible if we upload a file using terminal? by using curl maybe? and how to do it?
Thanks

**Comment by afterlogic-support** [comment]
This can be done via cURL indeed:
https://afterlogic.com/docs/aurora-files/developers-guide/using-web-api

**NB:** This tracker is for reporting issues. Community support is available at the [Forum](https://s.afterlogic.com/forum/forum_topics.asp?FID=30).
