### ISSUE TITLE
Shared With me error : "Data transfer failed, probably due to ...." at aurora files v.9.7.1

### ISSUE THREAD

**Issue by bellfoxace** [afterlogic/aurora-files#55]
The error related to file ../vendor/afterlogic/dav/lib/DAV/FS/Directory.php @ line 279

solved by:
// return filemtime($this->path);
return 0;  //  i follow the previous version of the script

I hope this error will be fix at next version caused in logs-error describe that syntax is depcrecated (perhaps PHP version), i use the PHP-8.2 latest version, and the previos aurora using old aurora-8.2.9 & PHP-7.4 version

regards,
Bellfox Ace

**Comment by afterlogic-support** [comment]
Thank you, I've asked the developers to take a look.

**Comment by afterlogic-support** [comment]
I believe the issue was fixed in version 9.7.2, would appreciate if you confirm whether the fix has worked.

**Comment by bellfoxace** [comment]
i have try reinstall aurora files with this new package, it's working fine,
the problem that I found is gone.
Thank you very much buddy, thank you for fast response & fast solving the
problem.

Would you tell me, is aurora files has such as schedule sharing by date, i
mean the sharing files limited between date, so it will release the sharing
if time reach. If this thread topics was discussed, let me know.

Thank You,
Bellfox Ace

**Comment by afterlogic-support** [comment]
Answered this at: https://github.com/afterlogic/aurora-files/issues/56
