### ISSUE TITLE
Error Message When Delete user

### ISSUE THREAD

**Issue by bellfoxace** [afterlogic/aurora-files#56]
i used aurora files ver.9.7.1, with PHP-8.2
case :
- create user : success
- delete user : success, but error message : Error While deleting user
- but user successes to deleted
- need reload (refresh page) for current list user status

Please advise or solve this problem, thank you.

**Comment by afterlogic-support** [comment]
Can you please confirm if the issue is still there in 9.7.2? Thank you.

**Comment by bellfoxace** [comment]
i have try reinstall aurora files with this new package, it's working fine,
the problem that I found is gone.
Thank you very much buddy, thank you for fast response & fast solving the
problem.

Would you tell me, is aurora files has such as schedule sharing by date, i
mean the sharing files limited between date, so it will release the sharing
if time reach. If this thread topics was discussed, let me know.

Thank You,

Regards,
Bellfox Ace

**Comment by afterlogic-support** [comment]
> But I've got the other problem, the indicator bar of quota is missing from both of  Personal / Share With Me main folder, beside corporate main folder is still showing.

Make sure you actually have a non-zero files quota for the user. If you have it set to non-zero value but the indicator still won't show, update the value by simply clicking Save on Files settings pane for the user in admin interface.

> Would you tell me, is aurora files has such as schedule sharing by date, i
mean the sharing files limited between date, so it will release the sharing
> if time reach. If this thread topics was discussed, let me know.

There's no such a feature. The closest you can have is public link expiry, enabled by setting "EnablePublicLinkLifetime" to **true** in `data/settings/modules/OpenPgpFilesWebclient.config.json`. Note that this requires OpenPGP enabled for Files.
