### ISSUE TITLE
Share Folder only 2 level recursive

### ISSUE THREAD

**Issue by bellfoxace** [afterlogic/aurora-files#57]
Hello,
My Server is using FreeBSD-13.2 stable, Apache-2.4.57, PHP-8.2.8, MariaDB-10.6.14.

I found error with sharing folder with teammates both of 9.7.2 and 9.7.3 version. The Erros show such as _**"Data transfer has failed, probably due to server error. Please contact system administrator."**_

I hope to you do steps what i've done, then The error above appears:
1st : register 2 account, let's say acc01@domain.com & acc02@domain.com
2nd : login at user acc01@domain.com, create tree folder in private channel such as : folders of **testing/123/456/789**
3rd : just do the sharing teammates for **testing** folder for acc01@domain.com
4th : login to user account acc02@domain.com, just enter to **testing** folder then enter to **123** folder, the error above will be appears here.

please, trying  practice and solve the problem above

just Fyi, i've try to debug inspector with firefox browser (ctrl+shift+K) keys, and repeat the step above or F5 (refresh browser), then i found the error below , who knows this error will be driving you to solve the problem on the track.

**_InstallTrigger is deprecated and will be removed in the future.         [app.min.js:2:87542]       app.min.js?972143)_**

I guess the problems are on PHP version or your scripts was deprecated syntax. Fyi, I never found this error with old version of aurora-files-9.6.0 with PHP-7.4.x version

​*Thank you*

**Comment by afterlogic-support** [comment]
> The Erros show such as "Data transfer has failed, probably due to server error. Please contact system administrator."

Please check this one: [https://afterlogic.com/docs/aurora-files/troubleshooting/data-transfer-has-failed](https://afterlogic.com/docs/aurora-files/troubleshooting/data-transfer-has-failed)

Most likely, you'll find errors in PHP/webserver logs, if you share the log entries we may be able to suggest how to proceed.
