### ISSUE TITLE
Can't extend User space limit and Upload file size limit

### ISSUE THREAD

**Issue by HiepNguyen1993** [afterlogic/aurora-files#6]
I was update User space limit and Upload file size limit but it not effect

**Comment by afterlogic-support** [comment]
Did you install it from a ZIP package? That one wasn't updated for some time but we've just published version 8.2.0, the issue should no longer be there. If it still remains, let us know.

**Comment by HiepNguyen1993** [comment]
Yeap, Thank you so much. I was use zip package and can't set max file size. After get lastes source, everything run perfect.

**Comment by afterlogic-support** [comment]
Any chance there's a tighter limit set in php configuration? See **PHP configuration** section of the following page:
https://afterlogic.com/docs/aurora-files/troubleshooting/error-while-uploading-to-files-storage

**Comment by HiepNguyen1993** [comment]
I'm deploying throught iis 10. I already set max request entity to 700MB but it still error. Default server limit 200MB but I update file .mp4 just 70MB it still error

**Comment by afterlogic-support** [comment]
So what values do you currently have for **upload_max_filesize** and **post_max_size** ?

**Comment by afterlogic-support** [comment]
Would it be possible to provide our developers with a test account on your installation? If yes, please send access details [via HelpDesk](https://s.afterlogic.com/helpdesk/). Thanks.

**Comment by HiepNguyen1993** [comment]
I was send a test account via HelpDesk. Thank you so much :+1:

**Comment by HiepNguyen1993** [comment]
Problem was solved. Because limit file size in iis 10 incorrect. Thank you very much.

**Comment by camielpeeters** [comment]
i have the same limit problem and have php max filesize and post_max_size on 5000mb but still no higher limit in client space than 100mb, what can this be?

**Comment by afterlogic-support** [comment]
Try adjusting the configuration in `data/settings/modules/Files.config.json` file. In current version, it looks like this:
```
    "EnableUploadSizeLimit": [
        true,
        "bool"
    ],
    "UploadSizeLimitMb": [
        100,
        "int"
    ],
    "UserSpaceLimitMb": [
        100,
        "int"
    ],
```

Hope this helps.

**Comment by natseg** [comment]
I don't know if there is a way to create a PR for the documentation hosted [here](https://afterlogic.com/docs/aurora-files/troubleshooting). I was struggling to find how to increase the 100 mb limit for my user. I am glad I found this issue and yes, I should have thought of looking in `files.config.json` but I didn't. :) 
Thanks for your hard work on this library.

**Comment by shakasha** [comment]
data/settings/modules/Files.config.json shows 10000 for "UserSpaceLimitMb" and I deleted and recreated the user and still hits the limit at 100MB. 
New install via zip and Composer. Version  8.3.7-build-a3

**Comment by shakasha** [comment]
{
    "Disabled": [
        false,
        "bool"
    ],
    "EnableUploadSizeLimit": [
        false,
        "bool"
    ],
    "UploadSizeLimitMb": [
        1000,
        "int"
    ],
    "UserSpaceLimitMb": [
        10000,
        "int"
    ],
    "TenantSpaceLimitMb": [
        0,
        "int"
    ]
}

**Comment by afterlogic-support** [comment]
Try increasing **UserSpaceLimitMb** value in `data/settings/modules/PersonalFiles.config.json` configuration file.

Does it help?

**Comment by shakasha** [comment]
Did not change anything and it is set to 100000 now which should 100GB.

    "UserSpaceLimitMb": [
        100000,
        "int"
    ],

**Comment by shakasha** [comment]
There is no data/settings/modules/PersonalFiles.config.json.

**Comment by afterlogic-support** [comment]
Probably it wasn't created for some reason; make sure to press "Update configuration" button in Database Settings screen of admin interface.

**Comment by shakasha** [comment]
That did the trick. Thank you so much!
