### ISSUE TITLE
Client Android not connect DAV

### ISSUE THREAD

**Issue by piratov** [afterlogic/aurora-files#60]
Client downloaded here https://afterlogic.org/aurora-files link https://play.google.com/store/apps/details?id=com.afterlogic.aurora.files
FormatException: Unexpected character (at character 1)
<?xml version="1.0" encoding="utf-8"?>
![image](https://github.com/afterlogic/aurora-files/assets/17856390/7d513694-656a-4e5a-8b05-8e3198b39091)

Clint windows is on connecting
![image](https://github.com/afterlogic/aurora-files/assets/17856390/d33c897b-c1a1-4635-b11a-fe3da666e43c)

**Comment by afterlogic-support** [comment]
For mobile app, this has to be the Aurora Files installation URL, not the DAV server URL.

**Comment by piratov** [comment]
> For mobile app, this has to be the Aurora Files installation URL, not the DAV server URL.

Only URL Thanks It works! 

Multi-language support planned?

**Comment by afterlogic-support** [comment]
There are no plans for that for the near future.
