### ISSUE TITLE
Password requirements settings ignored

### ISSUE THREAD

**Issue by anitdept** [afterlogic/aurora-files#62]
Hi.

I see in the config.json file there is an entry for both PasswordMinLength and PasswordMustBeComplex... but whenever I set these values, they seem to be ignored.  I can set whatever lame password I want, of any length I want.

Are these features not available yet, or is there something else that must be configured somewhere?  The logs don't seem to be showing me any errors.

Thanks.

**Comment by afterlogic-support** [comment]
These settings only apply to [password change modules](https://afterlogic.com/docs/webmail-pro/configuring-webmail/allow-users-to-change-account-passwords) which are designed to work with Afterlogic WebMail, and not with Aurora Files.

**Comment by anitdept** [comment]
That is unfortunate.  It looks like great software, but our auditors would never accept it as a solution without some way of enforcing a strong password.  Neither would the US government (who we also do business with).  Do you foresee that ever becoming a feature for AF?

Thanks anyway.
