### ISSUE TITLE
Last versions not in release

### ISSUE THREAD

**Issue by ayoahha** [afterlogic/aurora-files#64]
Hello
Wondering why the last version on release page is from 2022, whereas the last real version is from 2024 (from your website).
Did you closed some sources ?
Or is there any reasons ?

Many thanks

**Comment by afterlogic-support** [comment]
The product is open-source and is actively maintained. As you can see from the [VERSION](https://github.com/afterlogic/aurora-files/blob/master/VERSION) file, the repository holds the latest version 9.7.7 of the product. We simply don't use the Releases feature of GitHub anymore.

**Comment by ayoahha** [comment]
OK thanks for your reply
