### ISSUE TITLE
change directory after auto install

### ISSUE THREAD

**Issue by ciscoterminal** [afterlogic/aurora-files#8]
i have installed using this url
https://afterlogic.com/docs/aurora-files/installation/installing-on-debian-ubuntu-linux

now i want to change default login url from  localhosta/aurora-files to localhost or to localhost/xx
how can i do that

**Comment by afterlogic-support** [comment]
The product itself is installed under `/usr/share/aurora-files` directory, and the respective configuration file can be found under `/etc/apache2/conf-enabled/aurora-files.conf` so you can adjust the configuration file to provide a different URL.
