### ISSUE TITLE
official Docker images

### ISSUE THREAD

**Issue by alexanderadam** [afterlogic/aurora-files#9]
Hi folks,

thank you so much for Aurora. It would be nice if there would be an [official Docker image](https://hub.docker.com/u/afterlogic/) that includes a lightweight environment (i.e. [alpine](https://hub.docker.com/_/php?tab=tags) with nginx) though.

Thank you in advance and have a wonderful day!

**Comment by afterlogic-support** [comment]
Thank you for the suggestion. We're now experimenting with creating docker images on another project and will consider doing that for Aurora Files and our WebMail products, too.

**Comment by alexanderadam** [comment]
@afterlogic-support thank you for responding. But why is this issue closed although the image isn't available yet? :thinking: 

Wouldn't it make more sense to close this issue after it is actually resolved?

**Comment by afterlogic-support** [comment]
Oh, sorry. Of course you're right, let's keep it open.

**Comment by akhreiss** [comment]
Hello, any update on this post?

**Comment by afterlogic-support** [comment]
Not that I'm aware of, our current experiment with Docker is still ongoing.

**Comment by alexanderadam** [comment]
> Not that I'm aware of, our current experiment with Docker is still ongoing.

Is the `Dockerfile` of your experiment visible somewhere?
So that others could have look on it. It would be good if some of the best practices would be included (like [switching to an unprivileged user in the Dockerfile](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user) and using a small image [i.e. based on Alpine] with a small amount of layers).

**Comment by afterlogic-support** [comment]
It's not available yet but we'll make sure the project will be made available for public, within a few weeks most likely.

**Comment by tmladek** [comment]
Hello, any updates? This would greatly help adoption, I wager :)

**Comment by afterlogic-support** [comment]
We've just uploaded Docker images for our WebMail and Aurora products, including Aurora Files:
https://github.com/afterlogic/docker-aurora-files
https://hub.docker.com/r/afterlogic/docker-aurora-files
We've used the same approach as in our Ubuntu/Debian packages, with Apache+PHP+MySQL environment. In the future, we'll consider optimizing it and making more lightweight, and making official, too.
Your feedback is always appreciated, of course!

**Comment by alexanderadam** [comment]
Nice, will it be built for every release by a CI / GitHub actions?

**Comment by afterlogic-support** [comment]
Yes sure, we'll do our best to keep it up-to-date.

**Comment by alexanderadam** [comment]
Just in case I didn't make it obvious enough:

Thank you for your work! :pray:
